#!/bin/bash

while true
do
        

/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.18 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.11.116 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.18 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.56 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.18 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.68 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.18 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.24 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.18 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.0 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.41 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.26.56 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.41 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.60 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.124 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.41 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.64 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.18 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.6.120 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.48 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.8 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.41 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.28 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.41 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.4 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.32 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.11.20 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.112 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.120 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.14.56 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.80 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.36 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.72 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.42 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.20 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.48 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.76 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.48 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.2.120 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.48 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.2.56 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.48 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.26.120 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.48 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.16 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.48 --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.12 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102' 
/data/offshore_support/NSmediate/file_count.sh --user=guav_qus --host=144.226.255.48  --localdir=/data/feeds/NETSCOUT --remotedir=/data/mapper/incoming/qus/lte_dpi --includeip=10.32.116 --excludestring='DIAMETER|DNS|FTP_CONTROL|RADIUS_ACCESS|RADIUS_ACCT|GTPv2|MEDIA|PMIPV6|S1AP|S1MME|SIP|HTTPS|LDAP|GCSNA|S102'                                                                                                                                                                                  

#
done
#
